import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'mth-message-list',
  templateUrl: './message-list.component.html',
  styleUrls: ['./message-list.component.css']
})
export class MessageListComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

  dataSource = [
    { sender: 'Sommer Festival in the City', 
      subject: 'Subject Comes here', 
      desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.', 
      time: '12:30' },
    { sender: 'Sommer Festival in the City', 
    subject: 'Subject Comes here', 
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.', 
    time: '12:30' },
    { sender: 'Sommer Festival in the City', 
    subject: 'Subject Comes here', 
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.', 
    time: '12:30' },
    { sender: 'Sommer Festival in the City', 
    subject: 'Subject Comes here', 
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.', 
    time: '12:30' },
    { sender: 'Sommer Festival in the City', 
    subject: 'Subject Comes here', 
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.', 
    time: '12:30' },
    { sender: 'Sommer Festival in the City', 
    subject: 'Subject Comes here', 
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.', 
    time: '12:30' },
    { sender: 'Sommer Festival in the City', 
    subject: 'Subject Comes here', 
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.', 
    time: '12:30' },
    { sender: 'Sommer Festival in the City', 
    subject: 'Subject Comes here', 
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.', 
    time: '12:30' },
    { sender: 'Sommer Festival in the City', 
    subject: 'Subject Comes here', 
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.', 
    time: '12:30' },
    { sender: 'Sommer Festival in the City', 
    subject: 'Subject Comes here', 
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.', 
    time: '12:30' },
    { sender: 'Sommer Festival in the City', 
    subject: 'Subject Comes here', 
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.', 
    time: '12:30' },
    { sender: 'Sommer Festival in the City', 
    subject: 'Subject Comes here', 
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.', 
    time: '12:30' },
    { sender: 'Sommer Festival in the City', 
    subject: 'Subject Comes here', 
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.', 
    time: '12:30' },
    { sender: 'Sommer Festival in the City', 
    subject: 'Subject Comes here', 
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.', 
    time: '12:30' },
    { sender: 'Sommer Festival in the City', 
    subject: 'Subject Comes here', 
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.', 
    time: '12:30' },
    { sender: 'Sommer Festival in the City', 
    subject: 'Subject Comes here', 
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.', 
    time: '12:30' },
    { sender: 'Sommer Festival in the City', 
    subject: 'Subject Comes here', 
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.', 
    time: '12:30' },
    { sender: 'Sommer Festival in the City', 
    subject: 'Subject Comes here', 
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.', 
    time: '12:30' },
    { sender: 'Sommer Festival in the City', 
    subject: 'Subject Comes here', 
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.', 
    time: '12:30' },
    { sender: 'Sommer Festival in the City', 
    subject: 'Subject Comes here', 
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.', 
    time: '12:30' },
    { sender: 'Sommer Festival in the City', 
    subject: 'Subject Comes here', 
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.', 
    time: '12:30' }
  ];

  displayedColumns: string[] = ['sender', 'subject', 'desc', 'time'];
}
